name: file_share
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
 args: ^1.6.0 
 shelf: ^1.1.0
 shelf_router: ^1.0.0
 mime: ^1.0.0
 crypto: ^3.0.0

dev_dependencies:
  pedantic: ^1.9.0
